name: Windows

on:
  push:
    branches:
      - master  # Trigger on push
  pull_request:
    branches:
      - master  # Trigger on pull

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment for the build

    steps:
    - name: Checkout code
      uses: actions/checkout@v5  # Checkout the repository code

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v3  # Set up Visual Studio environment (MSBuild)

    - name: Configure CMake
      run: cmake -S . -B build  # Let CMake auto-detect the installed Visual Studio generator

    - name: Build
      run: cmake --build build --config Release  # Build the project using CMake with Release configuration

    - name: Run StdWorkerThreadApp
      run: .\build\Release\StdWorkerThreadApp.exe  # Run the built executable (adjust path for MSBuild)
